### ISSUE TITLE
moseq2 linux install appears to work but packages are not installed

### ISSUE THREAD

**Issue by burkheadjl** [dattalab/moseq2-app#261]
I could not find anything about this in the open issues: as I go through the Anaconda install, everything seems to work, but upon verifying that packages are installed, the error is that the files to not exist. I checked the appropriate directory under the anaconda environment and confirmed that the expected packages (extract, pca, etc.) are not installed
## Expected Behavior

when checking for example: moseq2-extract --version, the result should be
# moseq2-exract, version 1.1.2

## Current Behavior

(moseq2-app) copper2@anc-5rhs1v3:~/moseq2-app$ moseq2-extract --version
Traceback (most recent call last):
  File "/home/copper2/miniconda3/envs/moseq2-app/bin/moseq2-extract", line 5, in <module>
    from moseq2_extract.cli import cli
  File "/home/copper2/miniconda3/envs/moseq2-app/lib/python3.7/site-packages/moseq2_extract/cli.py", line 10, in <module>
    from moseq2_extract.util import command_with_config, read_yaml, recursive_find_unextracted_dirs
  File "/home/copper2/miniconda3/envs/moseq2-app/lib/python3.7/site-packages/moseq2_extract/util.py", line 6, in <module>
    import cv2
  File "/home/copper2/miniconda3/envs/moseq2-app/lib/python3.7/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libSM.so.6: cannot open shared object file: No such file or directory

## Steps to Reproduce (for bugs)

following anaconda install tutorial EXACTLY, then attempt to verify version
1.
2.
3.
4.

## Your Environment

* Version/GitHub branch used:
* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Link to your project:

**Comment by austin2118ace** [comment]
Ran into the same issue today on WSL. The following fixed the error:

```
sudo apt update
sudo apt install -y libsm6 libxext6 libxrender-dev
```
